author = "Chua Bok Woon"

[[pages]]
html = "post.html"
css = ["style.css"]
js = []
target = "pagemanager/blog/post.html"
    [pages.args]
    summary = "true"

[[pages]]
html = "post-index.html"
css = ["style.css"]
js = []
    [pages.args]
    ich = "nee"

["plainsimple/post-index.html"]
html = []
css = ["style.css"]
js = ["post-index.js"]

["plainsimple/post.html"]
html = []
css = ["style.css"]
js = ["post.js"]
